import type { NextPage } from 'next'
import Head from 'next/head'
import FastArticales from '../components/articales/FastArticales'
import Footer from '../components/shared/Footer'
import Header from '../components/shared/Header'
import styles from '../styles/Home.module.css'
import Mobileheader from '../components/shared/Mobileheader'
import MainContainer from '../components/articales/MainContainer'
import Navbar from '../components/shared/Navbar'

const myHead = () => {
  return <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=EB+Garamond:400,700,500,600italic,600&amp;display=swap"></link>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" />
  </Head>

}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>

        {/*  header */}
        <Navbar />

       {/* my head */}
       {myHead()}

      <div className="main-wrap content-main-wrap">

        {/*  header */}
        <Header />


        {/* mobile header */}
        <Mobileheader />

        {/* Fast Articales */}
        <FastArticales />

        {/* Main Container */}
        <MainContainer/>

        
        {/* Footer */}
        <Footer />

      </div>
    </div>
  )
}

export default Home
